# Generated by Django 4.2.7 on 2023-12-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weCare_App', '0003_alter_doctor_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='appointments',
            field=models.ManyToManyField(through='weCare_App.Appointment', to='weCare_App.patient'),
        ),
    ]
