# Generated by Django 4.2.7 on 2023-12-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weCare_App', '0004_alter_doctor_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patientppointment', to='weCare_App.patient'),
        ),
    ]
