# Generated by Django 5.0 on 2023-12-09 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weCare_App', '0006_alter_appointment_id_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patientppointment', to='weCare_App.patient'),
        ),
    ]
