# Generated by Django 5.0 on 2023-12-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weCare_App', '0005_alter_appointment_patient'),
        ('weCare_App', '0007_alter_appointment_patient'),
    ]

    operations = [
    ]
