# Generated by Django 4.2.7 on 2023-12-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weCare_App', '0005_alter_appointment_patient'),
        ('weCare_App', '0007_alter_appointment_patient'),
    ]

    operations = [
    ]
